### ISSUE TITLE
Что такое очередь касс?

### ISSUE THREAD

**Issue by PiskunovSS** [itrcz/smorodina_kkt_api#1]
Ошибка 9 "Очередь касс переполнена (Только для Receipt/ReceiptSync/Correction/CorrectionSync)".

1. Когда она возникает? 
2. Где хранится очередь? 
3. С какой скоростью обрабатывается? 
4. Как избежать данной ошибки при необходимости пробить 100000 чеков в сутки? (нужно после закрытия расчетного периода отразить все зачеты авансов в этом расчетном периоде в течении 10-ти дней после закрытия периода, с учетом размера баз РГК, чтобы успеть за 10 дней, нужно пробивать по 100000)
5. Сколько нужно касс для фискализации 100000 чеков в сутки?
6. Можно ли совсем убрать ограничение очереди? если нет, то почему?

**Comment by itrcz** [comment]
1) при 300 не пробитых чеков в очереди
2) в БД
3) до 3 чеков в секунду на 1 ККТ
4) Ошибки избегать не обязательно, нужно заложить ее в логику, если она возникает, значит система слишком интенсивно отправляет чеки и стоит понизить интенсивность отправки (ккт не успевают пробивать чеки) если же ошибка не возникаем можно увеличить интенсивность
5) 2 кассы минимум
6) Убрать совсем не получится, ограничение сделано для сглаживания пиковых нагрузок. Можно увеличить по согласованию

**Comment by PiskunovSS** [comment]
Спасибо
